apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiger-app
  template:
    metadata:
      labels:
        app: tiger-app
    spec:
      containers:
      - name: tiger-container
        # Sostituiamo nginx con la tua immagine reale
        image: giacomo12305/the-tiger-app:latest 
        ports:
        - containerPort: 5000 # Flask usa la 5000, non la 80!
