apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tiger-app
  template:
    metadata:
      labels:
        app: tiger-app
    spec:
      containers:
      - name: tiger-container
        image: nginx # Per ora usiamo nginx, poi Jenkins lo cambier√† con la tua immagine
        ports:
        - containerPort: 80
