apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiger-jenkins-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiger-jenkins-binding
subjects:
  - kind: ServiceAccount
    name: tiger-jenkins-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit # Permesso di modificare le risorse nel cluster
  apiGroup: rbac.authorization.k8s.io
