apiVersion: v1
kind: Service
metadata:
  name: tiger-service
spec:
  selector:
    app: tiger-app
  ports:
    - protocol: TCP
      port: 80         # La porta che scriverai nel browser
      targetPort: 5000  # La porta dove risponde Flask dentro il pod
  type: NodePort       # Cambialo in NodePort per vederlo dall'esterno della VM
